const statesEnum = {
    BASE: 'BASE',
    SALE_INITIATED: 'SALE_INITIATED',
    SALE_ACCEPTED: 'SALE_ACCEPTED',
    DOC_UPLOADED: 'DOC_UPLOADED',
    DOC_APPROVED: 'DOC_APPROVED',
    TX_INITIATED: 'TX_INITIATED', 
    TX_ACKNOWLEDGED: 'TX_ACKNOWLEDGED',
    CLOSED: 'CLOSED',
};

module.exports = statesEnum;